import type { Metadata } from "next";
import "@/assets/style/global.css";
import { geistMono, geistSans } from "@/assets/fonts/fontDefinitions";
import Link from "next/link";
import Footer from "./_ui/Footer";

export const metadata: Metadata = {
  title: {
    absolute: "Kestion · Homepage",
    template: "Kestion · %s",
  },
  description: "Generated by create next app",
  authors: [
    {
      name: "NZANZU MUHAYRWA L.",
      url: "https://amaru.onrender.com",
    },
  ],
  keywords: ["Blog", "Kestion", "NextJs"],
  publisher: "Vercel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <section className="hero">
          <header className="layout__header">
            <Link href="/" className="logo__link">
              Kestion
            </Link>
            <div className="actions">
              <Link href="/" className="text__btn">
                Log In
              </Link>
            </div>
          </header>
        </section>
        {children}
        <Footer />
      </body>
    </html>
  );
}
